{
 "title": "Dyson Fan",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(fan_mode, instance)"
   },
   { "name": "name", "label": "Device", "query": "label_values(fan_mode, name)" }
  ]
 },
 "panels": [
  { "title": "Current Operation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fan Mode",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "dyson_fan_mode{instance=~\"$instance\",name=~\"$name\"}==1",
     "legendFormat": "{{dyson_fan_mode}}"
    }
   ]
  },
  {
   "title": "Fan State",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "dyson_fan_state{instance=~\"$instance\",name=~\"$name\"}==1",
     "legendFormat": "{{dyson_fan_state}}"
    }
   ]
  },
  {
   "title": "Oscillation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "dyson_oscillation_mode{instance=~\"$instance\",name=~\"$name\"}==1",
     "legendFormat": "{{dyson_oscillation_mode}}"
    }
   ]
  },
  {
   "title": "Focus Mode",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "dyson_focus_mode{instance=~\"$instance\",name=~\"$name\"}==1",
     "legendFormat": "{{dyson_focus_mode}}"
    }
   ]
  },
  {
   "title": "Heat Mode",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "dyson_heat_mode{instance=~\"$instance\",name=~\"$name\"}==1",
     "legendFormat": "{{dyson_heat_mode}}"
    }
   ]
  },
  {
   "title": "Heat State",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "heat_state{instance=~\"$instance\",name=~\"$name\"}==1",
     "legendFormat": "{{heat_state}}"
    }
   ]
  },
  {
   "title": "Filter Life Remaining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dyson_filter_life_seconds{instance=~\"$instance\",name=~\"$name\"}"
    }
   ]
  },
  { "title": "Environmental", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Air Quality",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dyson_dust_units{instance=~\"$instance\",name=~\"$name\"}",
     "legendFormat": "Dust"
    },
    {
     "expr": "dyson_volatile_organic_compounds_units{instance=~\"$instance\",name=~\"$name\"}",
     "legendFormat": "VOC"
    },
    {
     "expr": "dyson_quality_target_units{instance=~\"$instance\",name=~\"$name\"}",
     "legendFormat": "Target"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dyson_humidity_percent{instance=~\"$instance\",name=~\"$name\"}",
     "legendFormat": "Humidity (%age)"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "dyson_temperature_celsius{instance=~\"$instance\",name=~\"$name\"}",
     "legendFormat": "Temperature"
    },
    {
     "expr": "dyson_heat_target_celsius{instance=~\"$instance\",name=~\"$name\"}",
     "legendFormat": "Heat Target"
    }
   ]
  },
  { "title": "Device Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Filter Life",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "dyson_filter_life_seconds{instance=~\"$instance\",name=~\"$name\"}",
     "legendFormat": "Remaining Life - {{name}}"
    }
   ]
  }
 ]
}